# Generated by Django 5.1.6 on 2025-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
